### ISSUE TITLE
Add boolean functions for checking: nom's `is_` equivalent

### ISSUE THREAD

**Issue by mainrs** [Alexhuszagh/rust-nom-unicode#3]
`nom` does define boolean functions to check if a char does satisfy the conditions. They can be found here: https://docs.rs/nom/6.0.0-alpha1/nom/character/index.html#functions

**Comment by mainrs** [comment]
I can open up a PR for this if you want to, just let me know. Same applies for issue #2 @Alexhuszagh. It's just a matter of adding the `pub` keyword to the functions.

**Comment by SirWindfield** [comment]
> 
> 
> I can open up a PR for this if you want to, just let me know. Same applies for issue #2 @Alexhuszagh.

**Comment by Alexhuszagh** [comment]
Live as of [v0.2](https://crates.io/crates/nom-unicode).
